/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package coursework;

import java.awt.HeadlessException;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JList;

public class InsertStudent extends javax.swing.JFrame {

    /**
     * Creates new form InsertPerson
     */
    public InsertStudent() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFirstName = new javax.swing.JLabel();
        lblLastName = new javax.swing.JLabel();
        lblAge = new javax.swing.JLabel();
        lblFNumber = new javax.swing.JLabel();
        lblKurs = new javax.swing.JLabel();
        jtfFirstName = new javax.swing.JTextField();
        jtfLastName = new javax.swing.JTextField();
        jtfAge = new javax.swing.JTextField();
        jtfFNumber = new javax.swing.JTextField();
        jtfKurs = new javax.swing.JTextField();
        btnInsertStudent = new javax.swing.JButton();
        btnWriteToFile = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstStudents = new javax.swing.JList<>();
        btnShowList = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblFirstName.setText("First Name:");

        lblLastName.setText("Last Name:");

        lblAge.setText("Age:");

        lblFNumber.setText("F. Number:");

        lblKurs.setText("Kurs");

        btnInsertStudent.setText("Instert Student");
        btnInsertStudent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnInsertStudentMouseClicked(evt);
            }
        });

        btnWriteToFile.setText("Write in File");
        btnWriteToFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWriteToFileActionPerformed(evt);
            }
        });

        lstStudents.setModel(new DefaultListModel());
        jScrollPane1.setViewportView(lstStudents);

        btnShowList.setText("Show List");
        btnShowList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowListActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFirstName)
                            .addComponent(lblLastName)
                            .addComponent(lblAge)
                            .addComponent(lblFNumber)
                            .addComponent(lblKurs))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jtfLastName, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                .addComponent(jtfKurs, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                .addComponent(jtfAge, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                .addComponent(jtfFNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                .addComponent(jtfFirstName))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnInsertStudent)
                                .addGap(50, 50, 50)
                                .addComponent(btnShowList)
                                .addGap(44, 44, 44)
                                .addComponent(btnWriteToFile))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFirstName)
                    .addComponent(jtfFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLastName)
                    .addComponent(jtfLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAge)
                    .addComponent(jtfAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFNumber)
                    .addComponent(jtfFNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblKurs)
                    .addComponent(jtfKurs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInsertStudent)
                    .addComponent(btnWriteToFile)
                    .addComponent(btnShowList))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInsertStudentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInsertStudentMouseClicked
        String FirstName = "";
        String LastName = "";
        int Age = 0;
        long FNumber = 0;
        int Kurs = 0;
        boolean[] flag = new boolean[5];
        if (!"".equals(jtfFirstName.getText())) {
            if (jtfFirstName.getText().matches("[a-zA-Z]+") && jtfFirstName.getText().length() > 2) {
                FirstName = jtfFirstName.getText();
                flag[0] = true;
            } else {
                ShowMessage.infoBox("Incorect First Name", "Error: Incorect Information");
                jtfFirstName.setText("");
            }
        } else {
            ShowMessage.infoBox("Please Insert First Name", "Error: Missing Information");
        }
        if (!"".equals(jtfLastName.getText())) {
            if (jtfLastName.getText().matches("[a-zA-Z]+") && jtfLastName.getText().length() > 2) {
                LastName = jtfLastName.getText();
                flag[1] = true;
            } else {
                jtfLastName.setText("");
                ShowMessage.infoBox("Incorect Last Name", "Error: Incorect Information");
            }
        } else {
            ShowMessage.infoBox("Please Insert Last Name", "Error: Missing Information");
        }
        if (!"".equals(jtfAge.getText())) {
            if (jtfAge.getText().matches("[0-9]+")) {
                Age = Integer.parseInt(jtfAge.getText());

                flag[2] = true;
            } else {
                jtfAge.setText("");
                ShowMessage.infoBox("Incorect Age", "Error: Incorect Information");
            }
        } else {
            ShowMessage.infoBox("Please Insert Age", "Error: Missing Information");
        }
        if (!"".equals(jtfFNumber.getText())) {
            if (jtfFNumber.getText().matches("[0-9]+")) {
                FNumber = Integer.parseInt(jtfFNumber.getText());

                flag[3] = true;
            } else {
                jtfFNumber.setText("");
                ShowMessage.infoBox("Incorect F. Number", "Error: Incorect Information");
            }
        } else {
            ShowMessage.infoBox("Please Insert F. Number", "Error: Missing Information");
        }
        if (!"".equals(jtfKurs.getText())) {
            if (jtfKurs.getText().matches("[0-9]+")) {
                Kurs = Integer.parseInt(jtfKurs.getText());
                flag[4] = true;
            } else {
                ShowMessage.infoBox("Incorect Kurs", "Error: Incorect Information");
                jtfKurs.setText("");
            }
        } else {
            ShowMessage.infoBox("Please Insert Kurs", "Error: Missing Information");
        }
        if (areAllTrue(flag)) {
            Student s = new Student(FNumber, Kurs, FirstName, LastName, Age);
            StudentList.add(s);
            jtfFirstName.setText("");
            jtfLastName.setText("");
            jtfAge.setText("");
            jtfFNumber.setText("");
            jtfKurs.setText("");
        }
// TODO add your handling code here:
    }//GEN-LAST:event_btnInsertStudentMouseClicked

    private void btnWriteToFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWriteToFileActionPerformed
        String file_name = "D:\\Students.txt";
        try {
            new PrintWriter(file_name).close();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(InsertStudent.class.getName()).log(Level.SEVERE, null, ex);
        }

        try {
            FileWrite data = new FileWrite(file_name, true);
            for (Object item : StudentList) {
                data.writeToFile(item.toString());
            }
        } catch (IOException e) {
            System.out.println(e.getMessage());
        }

        try {
            FileRead file = new FileRead(file_name);
            String[] aryLines = file.OpenFile();

            for (String aryLine : aryLines) {
                System.out.println(aryLine);
            }
        } catch (IOException e) {
            System.out.println(e.getMessage());
        }        // TODO add your handling code here:


    }//GEN-LAST:event_btnWriteToFileActionPerformed

    private void btnShowListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowListActionPerformed
        // TODO add your handling code here:
        for (Iterator it = StudentList.iterator(); it.hasNext();) {
            Object item = it.next();
            ((DefaultListModel)this.lstStudents.getModel()).addElement(item);
        }
        
    }//GEN-LAST:event_btnShowListActionPerformed

    public InsertStudent(JList<String> lstStudents) throws HeadlessException {
        this.lstStudents = lstStudents;
    }

    public static boolean areAllTrue(boolean[] array) {
        for (boolean b : array) {
            if (!b) {
                return false;
            }
        }
        return true;
    }
    ArrayList StudentList = new ArrayList();

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InsertStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new InsertStudent().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInsertStudent;
    private javax.swing.JButton btnShowList;
    private javax.swing.JButton btnWriteToFile;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jtfAge;
    private javax.swing.JTextField jtfFNumber;
    private javax.swing.JTextField jtfFirstName;
    private javax.swing.JTextField jtfKurs;
    private javax.swing.JTextField jtfLastName;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblFNumber;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblKurs;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JList<String> lstStudents;
    // End of variables declaration//GEN-END:variables
}
